IP_API = "https://api.ipify.org/?format=json"
GEO_API = "http://ip-api.com/json/{}"
WEATHER_API = "https://api.open-meteo.com/v1/forecast?latitude={}&longitude={}&hourly={}&current_weather=true&past_days=2"

FEATURES = [
    "temperature_2m",
    "relativehumidity_2m",
    "dewpoint_2m",
    "apparent_temperature",
    "pressure_msl",
    "precipitation",
    "weathercode",
    "snow_depth",
    "freezinglevel_height",
    "cloudcover",
    "cloudcover_low",
    "cloudcover_mid",
    "cloudcover_high",
    "shortwave_radiation",
    "direct_radiation",
    "diffuse_radiation",
    "direct_normal_irradiance",
    "evapotranspiration",
    "vapor_pressure_deficit",
    "windspeed_10m",
    "windspeed_80m",
    "windspeed_120m",
    "windspeed_180m",
    "winddirection_10m",
    "winddirection_80m",
    "winddirection_120m",
    "winddirection_180m",
    "windgusts_10m",
    "soil_temperature_0cm",
    "soil_temperature_6cm",
    "soil_temperature_18cm",
    "soil_temperature_54cm",
    "soil_moisture_0_1cm",
    "soil_moisture_1_3cm",
    "soil_moisture_3_9cm",
    "soil_moisture_9_27cm",
    "soil_moisture_27_81cm"
]
