from datetime import datetime
from typing import List

from pydantic import BaseModel


class Weather(BaseModel):
    time: List[datetime]
    temperature_2m: List[float]
    relativehumidity_2m: List[float]
    dewpoint_2m: List[float]
    apparent_temperature: List[float]
    pressure_msl: List[float]
    precipitation: List[float]
    weathercode: List[float]
    snow_depth: List[float]
    freezinglevel_height: List[float]
    cloudcover: List[float]
    cloudcover_low: List[float]
    cloudcover_mid: List[float]
    cloudcover_high: List[float]
    shortwave_radiation: List[float]
    direct_radiation: List[float]
    diffuse_radiation: List[float]
    direct_normal_irradiance: List[float]
    evapotranspiration: List[float]
    vapor_pressure_deficit: List[float]
    windspeed_10m: List[float]
    windspeed_80m: List[float]
    windspeed_120m: List[float]
    windspeed_180m: List[float]
    winddirection_10m: List[float]
    winddirection_80m: List[float]
    winddirection_120m: List[float]
    winddirection_180m: List[float]
    windgusts_10m: List[float]
    soil_temperature_0cm: List[float]
    soil_temperature_6cm: List[float]
    soil_temperature_18cm: List[float]
    soil_temperature_54cm: List[float]
    soil_moisture_0_1cm: List[float]
    soil_moisture_1_3cm: List[float]
    soil_moisture_3_9cm: List[float]
    soil_moisture_9_27cm: List[float]
    soil_moisture_27_81cm: List[float]
